apiVersion: v1
kind: Service
metadata:
  name: express-app
  labels:
    app: express-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 5200
      nodePort: 30000
  selector:
    app: express-app
